# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtd_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw(object):
    def setupUi(self, mw):
        mw.setObjectName("mw")
        mw.resize(1152, 864)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mw.sizePolicy().hasHeightForWidth())
        mw.setSizePolicy(sizePolicy)
        mw.setMinimumSize(QtCore.QSize(1152, 864))
        mw.setWindowTitle("Pazaak")
        mw.setAccessibleName("")
        mw.setAccessibleDescription("")
        mw.setStyleSheet("background-color: rgb(0, 0, 0);")
        mw.setWindowFilePath("")
        self.cw = QtWidgets.QWidget(mw)
        self.cw.setAccessibleName("")
        self.cw.setAccessibleDescription("")
        self.cw.setObjectName("cw")
        self.gridLayout = QtWidgets.QGridLayout(self.cw)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sw = QtWidgets.QStackedWidget(self.cw)
        self.sw.setMaximumSize(QtCore.QSize(1152, 864))
        self.sw.setAccessibleName("")
        self.sw.setAccessibleDescription("")
        self.sw.setObjectName("sw")
        self.sw_main_menu = QtWidgets.QWidget()
        self.sw_main_menu.setAccessibleName("")
        self.sw_main_menu.setAccessibleDescription("")
        self.sw_main_menu.setObjectName("sw_main_menu")
        self.mm_bg = QtWidgets.QLabel(self.sw_main_menu)
        self.mm_bg.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.mm_bg.setAccessibleName("")
        self.mm_bg.setAccessibleDescription("")
        self.mm_bg.setStyleSheet("background-color: lightgray")
        self.mm_bg.setText("")
        self.mm_bg.setObjectName("mm_bg")
        self.mm_btn_start = QtWidgets.QPushButton(self.sw_main_menu)
        self.mm_btn_start.setGeometry(QtCore.QRect(486, 342, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mm_btn_start.setFont(font)
        self.mm_btn_start.setAccessibleName("")
        self.mm_btn_start.setAccessibleDescription("")
        self.mm_btn_start.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.mm_btn_start.setText("START")
        self.mm_btn_start.setObjectName("mm_btn_start")
        self.mm_btn_help = QtWidgets.QPushButton(self.sw_main_menu)
        self.mm_btn_help.setGeometry(QtCore.QRect(486, 412, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mm_btn_help.setFont(font)
        self.mm_btn_help.setAccessibleName("")
        self.mm_btn_help.setAccessibleDescription("")
        self.mm_btn_help.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.mm_btn_help.setText("HELP")
        self.mm_btn_help.setObjectName("mm_btn_help")
        self.mm_btn_exit = QtWidgets.QPushButton(self.sw_main_menu)
        self.mm_btn_exit.setGeometry(QtCore.QRect(486, 482, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mm_btn_exit.setFont(font)
        self.mm_btn_exit.setAccessibleName("")
        self.mm_btn_exit.setAccessibleDescription("")
        self.mm_btn_exit.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.mm_btn_exit.setText("EXIT")
        self.mm_btn_exit.setObjectName("mm_btn_exit")
        self.temp_mm_title = QtWidgets.QLabel(self.sw_main_menu)
        self.temp_mm_title.setGeometry(QtCore.QRect(392, 108, 369, 109))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(44)
        font.setBold(False)
        font.setWeight(50)
        self.temp_mm_title.setFont(font)
        self.temp_mm_title.setStyleSheet("background-color: transparent")
        self.temp_mm_title.setText("Pazaak")
        self.temp_mm_title.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_mm_title.setObjectName("temp_mm_title")
        self.sw.addWidget(self.sw_main_menu)
        self.sw_deck_builder = QtWidgets.QWidget()
        self.sw_deck_builder.setAccessibleName("")
        self.sw_deck_builder.setAccessibleDescription("")
        self.sw_deck_builder.setObjectName("sw_deck_builder")
        self.db_bg = QtWidgets.QLabel(self.sw_deck_builder)
        self.db_bg.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.db_bg.setAccessibleName("")
        self.db_bg.setAccessibleDescription("")
        self.db_bg.setStyleSheet("background-color: lightgray")
        self.db_bg.setText("")
        self.db_bg.setObjectName("db_bg")
        self.db_btn_play = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_btn_play.setGeometry(QtCore.QRect(936, 32, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.db_btn_play.setFont(font)
        self.db_btn_play.setAccessibleName("")
        self.db_btn_play.setAccessibleDescription("")
        self.db_btn_play.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_btn_play.setText("PLAY")
        self.db_btn_play.setObjectName("db_btn_play")
        self.db_btn_back = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_btn_back.setGeometry(QtCore.QRect(36, 32, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.db_btn_back.setFont(font)
        self.db_btn_back.setAccessibleName("")
        self.db_btn_back.setAccessibleDescription("")
        self.db_btn_back.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_btn_back.setText("BACK TO MAIN")
        self.db_btn_back.setObjectName("db_btn_back")
        self.db_plus_1 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_plus_1.setGeometry(QtCore.QRect(254, 72, 94, 128))
        self.db_plus_1.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_plus_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/card_plus_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_plus_1.setIcon(icon)
        self.db_plus_1.setIconSize(QtCore.QSize(94, 128))
        self.db_plus_1.setObjectName("db_plus_1")
        self.db_plus_2 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_plus_2.setGeometry(QtCore.QRect(364, 72, 94, 128))
        self.db_plus_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_plus_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/card_plus_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_plus_2.setIcon(icon1)
        self.db_plus_2.setIconSize(QtCore.QSize(94, 128))
        self.db_plus_2.setObjectName("db_plus_2")
        self.db_plus_3 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_plus_3.setGeometry(QtCore.QRect(474, 72, 94, 128))
        self.db_plus_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_plus_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/card_plus_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_plus_3.setIcon(icon2)
        self.db_plus_3.setIconSize(QtCore.QSize(94, 128))
        self.db_plus_3.setObjectName("db_plus_3")
        self.db_plus_4 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_plus_4.setGeometry(QtCore.QRect(584, 72, 94, 128))
        self.db_plus_4.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_plus_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/card_plus_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_plus_4.setIcon(icon3)
        self.db_plus_4.setIconSize(QtCore.QSize(94, 128))
        self.db_plus_4.setObjectName("db_plus_4")
        self.db_plus_5 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_plus_5.setGeometry(QtCore.QRect(694, 72, 94, 128))
        self.db_plus_5.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_plus_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/card_plus_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_plus_5.setIcon(icon4)
        self.db_plus_5.setIconSize(QtCore.QSize(94, 128))
        self.db_plus_5.setObjectName("db_plus_5")
        self.db_plus_6 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_plus_6.setGeometry(QtCore.QRect(804, 72, 94, 128))
        self.db_plus_6.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_plus_6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("assets/card_plus_6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_plus_6.setIcon(icon5)
        self.db_plus_6.setIconSize(QtCore.QSize(94, 128))
        self.db_plus_6.setObjectName("db_plus_6")
        self.db_minus_1 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_minus_1.setGeometry(QtCore.QRect(254, 216, 94, 128))
        self.db_minus_1.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_minus_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("assets/card_minus_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_minus_1.setIcon(icon6)
        self.db_minus_1.setIconSize(QtCore.QSize(94, 128))
        self.db_minus_1.setObjectName("db_minus_1")
        self.db_minus_2 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_minus_2.setGeometry(QtCore.QRect(364, 216, 94, 128))
        self.db_minus_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_minus_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("assets/card_minus_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_minus_2.setIcon(icon7)
        self.db_minus_2.setIconSize(QtCore.QSize(94, 128))
        self.db_minus_2.setObjectName("db_minus_2")
        self.db_minus_3 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_minus_3.setGeometry(QtCore.QRect(474, 216, 94, 128))
        self.db_minus_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_minus_3.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("assets/card_minus_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_minus_3.setIcon(icon8)
        self.db_minus_3.setIconSize(QtCore.QSize(94, 128))
        self.db_minus_3.setObjectName("db_minus_3")
        self.db_minus_4 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_minus_4.setGeometry(QtCore.QRect(584, 216, 94, 128))
        self.db_minus_4.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_minus_4.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("assets/card_minus_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_minus_4.setIcon(icon9)
        self.db_minus_4.setIconSize(QtCore.QSize(94, 128))
        self.db_minus_4.setObjectName("db_minus_4")
        self.db_minus_5 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_minus_5.setGeometry(QtCore.QRect(694, 216, 94, 128))
        self.db_minus_5.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_minus_5.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("assets/card_minus_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_minus_5.setIcon(icon10)
        self.db_minus_5.setIconSize(QtCore.QSize(94, 128))
        self.db_minus_5.setObjectName("db_minus_5")
        self.db_minus_6 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_minus_6.setGeometry(QtCore.QRect(804, 216, 94, 128))
        self.db_minus_6.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_minus_6.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("assets/card_minus_6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_minus_6.setIcon(icon11)
        self.db_minus_6.setIconSize(QtCore.QSize(94, 128))
        self.db_minus_6.setObjectName("db_minus_6")
        self.db_dual_1 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_dual_1.setGeometry(QtCore.QRect(254, 360, 94, 128))
        self.db_dual_1.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_dual_1.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("assets/card_dual_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_dual_1.setIcon(icon12)
        self.db_dual_1.setIconSize(QtCore.QSize(94, 128))
        self.db_dual_1.setObjectName("db_dual_1")
        self.db_dual_2 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_dual_2.setGeometry(QtCore.QRect(364, 360, 94, 128))
        self.db_dual_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_dual_2.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("assets/card_dual_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_dual_2.setIcon(icon13)
        self.db_dual_2.setIconSize(QtCore.QSize(94, 128))
        self.db_dual_2.setObjectName("db_dual_2")
        self.db_dual_3 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_dual_3.setGeometry(QtCore.QRect(474, 360, 94, 128))
        self.db_dual_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_dual_3.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("assets/card_dual_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_dual_3.setIcon(icon14)
        self.db_dual_3.setIconSize(QtCore.QSize(94, 128))
        self.db_dual_3.setObjectName("db_dual_3")
        self.db_dual_4 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_dual_4.setGeometry(QtCore.QRect(586, 360, 94, 128))
        self.db_dual_4.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_dual_4.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("assets/card_dual_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_dual_4.setIcon(icon15)
        self.db_dual_4.setIconSize(QtCore.QSize(94, 128))
        self.db_dual_4.setObjectName("db_dual_4")
        self.db_dual_5 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_dual_5.setGeometry(QtCore.QRect(694, 360, 94, 128))
        self.db_dual_5.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_dual_5.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("assets/card_dual_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_dual_5.setIcon(icon16)
        self.db_dual_5.setIconSize(QtCore.QSize(94, 128))
        self.db_dual_5.setObjectName("db_dual_5")
        self.db_dual_6 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_dual_6.setGeometry(QtCore.QRect(804, 360, 94, 128))
        self.db_dual_6.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_dual_6.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("assets/card_dual_6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_dual_6.setIcon(icon17)
        self.db_dual_6.setIconSize(QtCore.QSize(94, 128))
        self.db_dual_6.setObjectName("db_dual_6")
        self.db_btn_random = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_btn_random.setGeometry(QtCore.QRect(640, 786, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.db_btn_random.setFont(font)
        self.db_btn_random.setAccessibleName("")
        self.db_btn_random.setAccessibleDescription("")
        self.db_btn_random.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_btn_random.setText("RANDOMIZE")
        self.db_btn_random.setObjectName("db_btn_random")
        self.db_btn_clear = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_btn_clear.setGeometry(QtCore.QRect(334, 786, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.db_btn_clear.setFont(font)
        self.db_btn_clear.setAccessibleName("")
        self.db_btn_clear.setAccessibleDescription("")
        self.db_btn_clear.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_btn_clear.setText("CLEAR")
        self.db_btn_clear.setObjectName("db_btn_clear")
        self.db_deck_5 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_deck_5.setGeometry(QtCore.QRect(478, 620, 94, 128))
        self.db_deck_5.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_deck_5.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("assets/card_base.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.db_deck_5.setIcon(icon18)
        self.db_deck_5.setIconSize(QtCore.QSize(94, 128))
        self.db_deck_5.setObjectName("db_deck_5")
        self.db_deck_4 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_deck_4.setGeometry(QtCore.QRect(376, 620, 94, 128))
        self.db_deck_4.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_deck_4.setText("")
        self.db_deck_4.setIcon(icon18)
        self.db_deck_4.setIconSize(QtCore.QSize(94, 128))
        self.db_deck_4.setObjectName("db_deck_4")
        self.db_deck_3 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_deck_3.setGeometry(QtCore.QRect(274, 620, 94, 128))
        self.db_deck_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_deck_3.setText("")
        self.db_deck_3.setIcon(icon18)
        self.db_deck_3.setIconSize(QtCore.QSize(94, 128))
        self.db_deck_3.setObjectName("db_deck_3")
        self.db_deck_2 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_deck_2.setGeometry(QtCore.QRect(172, 620, 94, 128))
        self.db_deck_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_deck_2.setText("")
        self.db_deck_2.setIcon(icon18)
        self.db_deck_2.setIconSize(QtCore.QSize(94, 128))
        self.db_deck_2.setObjectName("db_deck_2")
        self.db_deck_1 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_deck_1.setGeometry(QtCore.QRect(70, 620, 94, 128))
        self.db_deck_1.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_deck_1.setText("")
        self.db_deck_1.setIcon(icon18)
        self.db_deck_1.setIconSize(QtCore.QSize(94, 128))
        self.db_deck_1.setObjectName("db_deck_1")
        self.db_deck_6 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_deck_6.setGeometry(QtCore.QRect(580, 620, 94, 128))
        self.db_deck_6.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_deck_6.setText("")
        self.db_deck_6.setIcon(icon18)
        self.db_deck_6.setIconSize(QtCore.QSize(94, 128))
        self.db_deck_6.setObjectName("db_deck_6")
        self.db_deck_7 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_deck_7.setGeometry(QtCore.QRect(682, 620, 94, 128))
        self.db_deck_7.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_deck_7.setText("")
        self.db_deck_7.setIcon(icon18)
        self.db_deck_7.setIconSize(QtCore.QSize(94, 128))
        self.db_deck_7.setObjectName("db_deck_7")
        self.db_deck_8 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_deck_8.setGeometry(QtCore.QRect(784, 620, 94, 128))
        self.db_deck_8.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_deck_8.setText("")
        self.db_deck_8.setIcon(icon18)
        self.db_deck_8.setIconSize(QtCore.QSize(94, 128))
        self.db_deck_8.setObjectName("db_deck_8")
        self.db_deck_9 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_deck_9.setGeometry(QtCore.QRect(886, 620, 94, 128))
        self.db_deck_9.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_deck_9.setText("")
        self.db_deck_9.setIcon(icon18)
        self.db_deck_9.setIconSize(QtCore.QSize(94, 128))
        self.db_deck_9.setObjectName("db_deck_9")
        self.db_deck_10 = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_deck_10.setGeometry(QtCore.QRect(988, 620, 94, 128))
        self.db_deck_10.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.db_deck_10.setText("")
        self.db_deck_10.setIcon(icon18)
        self.db_deck_10.setIconSize(QtCore.QSize(94, 128))
        self.db_deck_10.setObjectName("db_deck_10")
        self.temp_db_text_available = QtWidgets.QLabel(self.sw_deck_builder)
        self.temp_db_text_available.setGeometry(QtCore.QRect(458, 22, 236, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.temp_db_text_available.setFont(font)
        self.temp_db_text_available.setStyleSheet("color: white")
        self.temp_db_text_available.setText("CARDS AVAILABLE")
        self.temp_db_text_available.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_db_text_available.setObjectName("temp_db_text_available")
        self.temp_db_text_deck = QtWidgets.QLabel(self.sw_deck_builder)
        self.temp_db_text_deck.setGeometry(QtCore.QRect(498, 570, 154, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.temp_db_text_deck.setFont(font)
        self.temp_db_text_deck.setStyleSheet("color: white")
        self.temp_db_text_deck.setText("YOUR DECK")
        self.temp_db_text_deck.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_db_text_deck.setObjectName("temp_db_text_deck")
        self.sw.addWidget(self.sw_deck_builder)
        self.sw_game_screen = QtWidgets.QWidget()
        self.sw_game_screen.setObjectName("sw_game_screen")
        self.gs_bg = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_bg.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.gs_bg.setAccessibleName("")
        self.gs_bg.setAccessibleDescription("")
        self.gs_bg.setStyleSheet("background-color: lightgray")
        self.gs_bg.setText("")
        self.gs_bg.setObjectName("gs_bg")
        self.gs_btn_help = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_btn_help.setGeometry(QtCore.QRect(560, 40, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.gs_btn_help.setFont(font)
        self.gs_btn_help.setAccessibleName("")
        self.gs_btn_help.setAccessibleDescription("")
        self.gs_btn_help.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_btn_help.setText("?")
        self.gs_btn_help.setObjectName("gs_btn_help")
        self.gs_btn_quit = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_btn_quit.setGeometry(QtCore.QRect(764, 800, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gs_btn_quit.setFont(font)
        self.gs_btn_quit.setAccessibleName("")
        self.gs_btn_quit.setAccessibleDescription("")
        self.gs_btn_quit.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_btn_quit.setText("QUIT MATCH")
        self.gs_btn_quit.setObjectName("gs_btn_quit")
        self.gs_opp_slot_1 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_slot_1.setGeometry(QtCore.QRect(696, 112, 94, 128))
        self.gs_opp_slot_1.setStyleSheet("background-color: transparent")
        self.gs_opp_slot_1.setText("")
        self.gs_opp_slot_1.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_slot_1.setObjectName("gs_opp_slot_1")
        self.gs_opp_slot_2 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_slot_2.setGeometry(QtCore.QRect(806, 112, 94, 128))
        self.gs_opp_slot_2.setStyleSheet("background-color: transparent")
        self.gs_opp_slot_2.setText("")
        self.gs_opp_slot_2.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_slot_2.setObjectName("gs_opp_slot_2")
        self.gs_opp_slot_3 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_slot_3.setGeometry(QtCore.QRect(916, 112, 94, 128))
        self.gs_opp_slot_3.setStyleSheet("background-color: transparent")
        self.gs_opp_slot_3.setText("")
        self.gs_opp_slot_3.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_slot_3.setObjectName("gs_opp_slot_3")
        self.gs_opp_slot_4 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_slot_4.setGeometry(QtCore.QRect(696, 250, 94, 128))
        self.gs_opp_slot_4.setStyleSheet("background-color: transparent")
        self.gs_opp_slot_4.setText("")
        self.gs_opp_slot_4.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_slot_4.setObjectName("gs_opp_slot_4")
        self.gs_opp_slot_5 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_slot_5.setGeometry(QtCore.QRect(806, 250, 94, 128))
        self.gs_opp_slot_5.setStyleSheet("background-color: transparent")
        self.gs_opp_slot_5.setText("")
        self.gs_opp_slot_5.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_slot_5.setObjectName("gs_opp_slot_5")
        self.gs_opp_slot_6 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_slot_6.setGeometry(QtCore.QRect(916, 250, 94, 128))
        self.gs_opp_slot_6.setStyleSheet("background-color: transparent")
        self.gs_opp_slot_6.setText("")
        self.gs_opp_slot_6.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_slot_6.setObjectName("gs_opp_slot_6")
        self.gs_opp_slot_7 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_slot_7.setGeometry(QtCore.QRect(696, 388, 94, 128))
        self.gs_opp_slot_7.setStyleSheet("background-color: transparent")
        self.gs_opp_slot_7.setText("")
        self.gs_opp_slot_7.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_slot_7.setObjectName("gs_opp_slot_7")
        self.gs_opp_slot_8 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_slot_8.setGeometry(QtCore.QRect(806, 388, 94, 128))
        self.gs_opp_slot_8.setStyleSheet("background-color: transparent")
        self.gs_opp_slot_8.setText("")
        self.gs_opp_slot_8.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_slot_8.setObjectName("gs_opp_slot_8")
        self.gs_opp_slot_9 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_slot_9.setGeometry(QtCore.QRect(916, 388, 94, 128))
        self.gs_opp_slot_9.setStyleSheet("background-color: transparent")
        self.gs_opp_slot_9.setText("")
        self.gs_opp_slot_9.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_slot_9.setObjectName("gs_opp_slot_9")
        self.gs_player_slot_1 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_slot_1.setGeometry(QtCore.QRect(142, 112, 94, 128))
        self.gs_player_slot_1.setStyleSheet("background-color: transparent")
        self.gs_player_slot_1.setText("")
        self.gs_player_slot_1.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_player_slot_1.setObjectName("gs_player_slot_1")
        self.gs_player_slot_2 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_slot_2.setGeometry(QtCore.QRect(252, 112, 94, 128))
        self.gs_player_slot_2.setStyleSheet("background-color: transparent")
        self.gs_player_slot_2.setText("")
        self.gs_player_slot_2.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_player_slot_2.setObjectName("gs_player_slot_2")
        self.gs_player_slot_3 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_slot_3.setGeometry(QtCore.QRect(362, 112, 94, 128))
        self.gs_player_slot_3.setStyleSheet("background-color: transparent")
        self.gs_player_slot_3.setText("")
        self.gs_player_slot_3.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_player_slot_3.setObjectName("gs_player_slot_3")
        self.gs_player_slot_4 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_slot_4.setGeometry(QtCore.QRect(142, 250, 94, 128))
        self.gs_player_slot_4.setStyleSheet("background-color: transparent")
        self.gs_player_slot_4.setText("")
        self.gs_player_slot_4.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_player_slot_4.setObjectName("gs_player_slot_4")
        self.gs_player_slot_5 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_slot_5.setGeometry(QtCore.QRect(252, 250, 94, 128))
        self.gs_player_slot_5.setStyleSheet("background-color: transparent")
        self.gs_player_slot_5.setText("")
        self.gs_player_slot_5.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_player_slot_5.setObjectName("gs_player_slot_5")
        self.gs_player_slot_6 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_slot_6.setGeometry(QtCore.QRect(362, 250, 94, 128))
        self.gs_player_slot_6.setStyleSheet("background-color: transparent")
        self.gs_player_slot_6.setText("")
        self.gs_player_slot_6.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_player_slot_6.setObjectName("gs_player_slot_6")
        self.gs_player_slot_7 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_slot_7.setGeometry(QtCore.QRect(142, 388, 94, 128))
        self.gs_player_slot_7.setStyleSheet("background-color: transparent")
        self.gs_player_slot_7.setText("")
        self.gs_player_slot_7.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_player_slot_7.setObjectName("gs_player_slot_7")
        self.gs_player_slot_8 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_slot_8.setGeometry(QtCore.QRect(252, 388, 94, 128))
        self.gs_player_slot_8.setStyleSheet("background-color: transparent")
        self.gs_player_slot_8.setText("")
        self.gs_player_slot_8.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_player_slot_8.setObjectName("gs_player_slot_8")
        self.gs_player_slot_9 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_slot_9.setGeometry(QtCore.QRect(362, 388, 94, 128))
        self.gs_player_slot_9.setStyleSheet("background-color: transparent")
        self.gs_player_slot_9.setText("")
        self.gs_player_slot_9.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_player_slot_9.setObjectName("gs_player_slot_9")
        self.gs_player_hand_1 = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_player_hand_1.setGeometry(QtCore.QRect(90, 574, 94, 128))
        self.gs_player_hand_1.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_player_hand_1.setText("")
        self.gs_player_hand_1.setIcon(icon18)
        self.gs_player_hand_1.setIconSize(QtCore.QSize(94, 128))
        self.gs_player_hand_1.setObjectName("gs_player_hand_1")
        self.gs_player_hand_2 = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_player_hand_2.setGeometry(QtCore.QRect(198, 574, 94, 128))
        self.gs_player_hand_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_player_hand_2.setText("")
        self.gs_player_hand_2.setIcon(icon18)
        self.gs_player_hand_2.setIconSize(QtCore.QSize(94, 128))
        self.gs_player_hand_2.setObjectName("gs_player_hand_2")
        self.gs_player_hand_3 = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_player_hand_3.setGeometry(QtCore.QRect(306, 574, 94, 128))
        self.gs_player_hand_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_player_hand_3.setText("")
        self.gs_player_hand_3.setIcon(icon18)
        self.gs_player_hand_3.setIconSize(QtCore.QSize(94, 128))
        self.gs_player_hand_3.setObjectName("gs_player_hand_3")
        self.gs_player_hand_4 = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_player_hand_4.setGeometry(QtCore.QRect(414, 574, 94, 128))
        self.gs_player_hand_4.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_player_hand_4.setText("")
        self.gs_player_hand_4.setIcon(icon18)
        self.gs_player_hand_4.setIconSize(QtCore.QSize(94, 128))
        self.gs_player_hand_4.setObjectName("gs_player_hand_4")
        self.gs_opp_hand_1 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_hand_1.setGeometry(QtCore.QRect(644, 574, 94, 128))
        self.gs_opp_hand_1.setStyleSheet("background-color: transparent")
        self.gs_opp_hand_1.setText("")
        self.gs_opp_hand_1.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_hand_1.setObjectName("gs_opp_hand_1")
        self.gs_opp_hand_2 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_hand_2.setGeometry(QtCore.QRect(752, 574, 94, 128))
        self.gs_opp_hand_2.setStyleSheet("background-color: transparent")
        self.gs_opp_hand_2.setText("")
        self.gs_opp_hand_2.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_hand_2.setObjectName("gs_opp_hand_2")
        self.gs_opp_hand_3 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_hand_3.setGeometry(QtCore.QRect(860, 574, 94, 128))
        self.gs_opp_hand_3.setStyleSheet("background-color: transparent")
        self.gs_opp_hand_3.setText("")
        self.gs_opp_hand_3.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_hand_3.setObjectName("gs_opp_hand_3")
        self.gs_opp_hand_4 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_hand_4.setGeometry(QtCore.QRect(968, 574, 94, 128))
        self.gs_opp_hand_4.setStyleSheet("background-color: transparent")
        self.gs_opp_hand_4.setText("")
        self.gs_opp_hand_4.setPixmap(QtGui.QPixmap("assets/card_base.png"))
        self.gs_opp_hand_4.setObjectName("gs_opp_hand_4")
        self.gs_player_turn = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_turn.setGeometry(QtCore.QRect(66, 30, 60, 60))
        self.gs_player_turn.setStyleSheet("background-color: transparent")
        self.gs_player_turn.setText("")
        self.gs_player_turn.setPixmap(QtGui.QPixmap("assets/turn_indicator.png"))
        self.gs_player_turn.setObjectName("gs_player_turn")
        self.gs_opp_turn = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_turn.setGeometry(QtCore.QRect(1026, 30, 60, 60))
        self.gs_opp_turn.setStyleSheet("background-color: transparent")
        self.gs_opp_turn.setText("")
        self.gs_opp_turn.setPixmap(QtGui.QPixmap("assets/turn_indicator.png"))
        self.gs_opp_turn.setObjectName("gs_opp_turn")
        self.gs_player_set_1 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_set_1.setGeometry(QtCore.QRect(76, 112, 40, 40))
        self.gs_player_set_1.setStyleSheet("background-color: transparent")
        self.gs_player_set_1.setText("")
        self.gs_player_set_1.setPixmap(QtGui.QPixmap("assets/set_inactive.png"))
        self.gs_player_set_1.setObjectName("gs_player_set_1")
        self.gs_player_set_2 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_set_2.setGeometry(QtCore.QRect(76, 160, 40, 40))
        self.gs_player_set_2.setStyleSheet("background-color: transparent")
        self.gs_player_set_2.setText("")
        self.gs_player_set_2.setPixmap(QtGui.QPixmap("assets/set_inactive.png"))
        self.gs_player_set_2.setObjectName("gs_player_set_2")
        self.gs_player_set_3 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_set_3.setGeometry(QtCore.QRect(76, 208, 40, 40))
        self.gs_player_set_3.setStyleSheet("background-color: transparent")
        self.gs_player_set_3.setText("")
        self.gs_player_set_3.setPixmap(QtGui.QPixmap("assets/set_inactive.png"))
        self.gs_player_set_3.setObjectName("gs_player_set_3")
        self.gs_opp_set_3 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_set_3.setGeometry(QtCore.QRect(1036, 208, 40, 40))
        self.gs_opp_set_3.setStyleSheet("background-color: transparent")
        self.gs_opp_set_3.setText("")
        self.gs_opp_set_3.setPixmap(QtGui.QPixmap("assets/set_inactive.png"))
        self.gs_opp_set_3.setObjectName("gs_opp_set_3")
        self.gs_opp_set_2 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_set_2.setGeometry(QtCore.QRect(1036, 160, 40, 40))
        self.gs_opp_set_2.setStyleSheet("background-color: transparent")
        self.gs_opp_set_2.setText("")
        self.gs_opp_set_2.setPixmap(QtGui.QPixmap("assets/set_inactive.png"))
        self.gs_opp_set_2.setObjectName("gs_opp_set_2")
        self.gs_opp_set_1 = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_set_1.setGeometry(QtCore.QRect(1036, 112, 40, 40))
        self.gs_opp_set_1.setStyleSheet("background-color: transparent")
        self.gs_opp_set_1.setText("")
        self.gs_opp_set_1.setPixmap(QtGui.QPixmap("assets/set_inactive.png"))
        self.gs_opp_set_1.setObjectName("gs_opp_set_1")
        self.gs_btn_endturn = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_btn_endturn.setGeometry(QtCore.QRect(656, 724, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gs_btn_endturn.setFont(font)
        self.gs_btn_endturn.setAccessibleName("")
        self.gs_btn_endturn.setAccessibleDescription("")
        self.gs_btn_endturn.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_btn_endturn.setText("END TURN")
        self.gs_btn_endturn.setObjectName("gs_btn_endturn")
        self.gs_btn_stand = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_btn_stand.setGeometry(QtCore.QRect(870, 724, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gs_btn_stand.setFont(font)
        self.gs_btn_stand.setAccessibleName("")
        self.gs_btn_stand.setAccessibleDescription("")
        self.gs_btn_stand.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_btn_stand.setText("STAND")
        self.gs_btn_stand.setObjectName("gs_btn_stand")
        self.gs_flip_1 = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_flip_1.setGeometry(QtCore.QRect(120, 712, 36, 36))
        self.gs_flip_1.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_flip_1.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("assets/flip_card.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gs_flip_1.setIcon(icon19)
        self.gs_flip_1.setIconSize(QtCore.QSize(36, 36))
        self.gs_flip_1.setObjectName("gs_flip_1")
        self.gs_flip_2 = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_flip_2.setGeometry(QtCore.QRect(228, 712, 36, 36))
        self.gs_flip_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_flip_2.setText("")
        self.gs_flip_2.setIcon(icon19)
        self.gs_flip_2.setIconSize(QtCore.QSize(36, 36))
        self.gs_flip_2.setObjectName("gs_flip_2")
        self.gs_flip_3 = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_flip_3.setGeometry(QtCore.QRect(336, 712, 36, 36))
        self.gs_flip_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_flip_3.setText("")
        self.gs_flip_3.setIcon(icon19)
        self.gs_flip_3.setIconSize(QtCore.QSize(36, 36))
        self.gs_flip_3.setObjectName("gs_flip_3")
        self.gs_flip_4 = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_flip_4.setGeometry(QtCore.QRect(444, 712, 36, 36))
        self.gs_flip_4.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.gs_flip_4.setText("")
        self.gs_flip_4.setIcon(icon19)
        self.gs_flip_4.setIconSize(QtCore.QSize(36, 36))
        self.gs_flip_4.setObjectName("gs_flip_4")
        self.temp_gs_player_name = QtWidgets.QLabel(self.sw_game_screen)
        self.temp_gs_player_name.setGeometry(QtCore.QRect(142, 44, 107, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.temp_gs_player_name.setFont(font)
        self.temp_gs_player_name.setStyleSheet("color: yellow")
        self.temp_gs_player_name.setText(" PLAYER")
        self.temp_gs_player_name.setObjectName("temp_gs_player_name")
        self.temp_gs_opp_name = QtWidgets.QLabel(self.sw_game_screen)
        self.temp_gs_opp_name.setGeometry(QtCore.QRect(864, 44, 146, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.temp_gs_opp_name.setFont(font)
        self.temp_gs_opp_name.setStyleSheet("color: yellow")
        self.temp_gs_opp_name.setText("OPPONENT ")
        self.temp_gs_opp_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp_gs_opp_name.setObjectName("temp_gs_opp_name")
        self.gs_player_total = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_player_total.setGeometry(QtCore.QRect(424, 44, 32, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.gs_player_total.setFont(font)
        self.gs_player_total.setStyleSheet("color: white")
        self.gs_player_total.setText("##")
        self.gs_player_total.setAlignment(QtCore.Qt.AlignCenter)
        self.gs_player_total.setObjectName("gs_player_total")
        self.gs_opp_total = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_opp_total.setGeometry(QtCore.QRect(696, 44, 32, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.gs_opp_total.setFont(font)
        self.gs_opp_total.setStyleSheet("color: white")
        self.gs_opp_total.setText("##")
        self.gs_opp_total.setAlignment(QtCore.Qt.AlignCenter)
        self.gs_opp_total.setObjectName("gs_opp_total")
        self.popup_match = QtWidgets.QFrame(self.sw_game_screen)
        self.popup_match.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.popup_match.setToolTip("")
        self.popup_match.setStatusTip("")
        self.popup_match.setWhatsThis("")
        self.popup_match.setAccessibleName("")
        self.popup_match.setAccessibleDescription("")
        self.popup_match.setStyleSheet("background-color: rgba(0, 0, 0, 150)")
        self.popup_match.setObjectName("popup_match")
        self.frame_match = QtWidgets.QFrame(self.popup_match)
        self.frame_match.setGeometry(QtCore.QRect(306, 304, 540, 160))
        self.frame_match.setToolTip("")
        self.frame_match.setStatusTip("")
        self.frame_match.setWhatsThis("")
        self.frame_match.setAccessibleName("")
        self.frame_match.setAccessibleDescription("")
        self.frame_match.setStyleSheet("background-color: rgba(0, 0, 0, 180);")
        self.frame_match.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_match.setLineWidth(2)
        self.frame_match.setObjectName("frame_match")
        self.text_info_match = QtWidgets.QLabel(self.frame_match)
        self.text_info_match.setGeometry(QtCore.QRect(130, 20, 280, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_info_match.setFont(font)
        self.text_info_match.setToolTip("")
        self.text_info_match.setStatusTip("")
        self.text_info_match.setWhatsThis("")
        self.text_info_match.setAccessibleName("")
        self.text_info_match.setAccessibleDescription("")
        self.text_info_match.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.text_info_match.setText("<insert match text here>")
        self.text_info_match.setAlignment(QtCore.Qt.AlignCenter)
        self.text_info_match.setObjectName("text_info_match")
        self.btn_ok_match = QtWidgets.QPushButton(self.frame_match)
        self.btn_ok_match.setGeometry(QtCore.QRect(200, 100, 140, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok_match.setFont(font)
        self.btn_ok_match.setStatusTip("")
        self.btn_ok_match.setWhatsThis("")
        self.btn_ok_match.setAccessibleName("")
        self.btn_ok_match.setAccessibleDescription("")
        self.btn_ok_match.setAutoFillBackground(False)
        self.btn_ok_match.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_ok_match.setText("OK")
        self.btn_ok_match.setDefault(True)
        self.btn_ok_match.setFlat(True)
        self.btn_ok_match.setObjectName("btn_ok_match")
        self.popup_set = QtWidgets.QFrame(self.sw_game_screen)
        self.popup_set.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.popup_set.setToolTip("")
        self.popup_set.setStatusTip("")
        self.popup_set.setWhatsThis("")
        self.popup_set.setAccessibleName("")
        self.popup_set.setAccessibleDescription("")
        self.popup_set.setStyleSheet("background-color: rgba(0, 0, 0, 150)")
        self.popup_set.setObjectName("popup_set")
        self.frame_set = QtWidgets.QFrame(self.popup_set)
        self.frame_set.setGeometry(QtCore.QRect(306, 304, 540, 160))
        self.frame_set.setToolTip("")
        self.frame_set.setStatusTip("")
        self.frame_set.setWhatsThis("")
        self.frame_set.setAccessibleName("")
        self.frame_set.setAccessibleDescription("")
        self.frame_set.setStyleSheet("background-color: rgba(0, 0, 0, 180);")
        self.frame_set.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_set.setLineWidth(2)
        self.frame_set.setObjectName("frame_set")
        self.text_info_set = QtWidgets.QLabel(self.frame_set)
        self.text_info_set.setGeometry(QtCore.QRect(130, 20, 280, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_info_set.setFont(font)
        self.text_info_set.setToolTip("")
        self.text_info_set.setStatusTip("")
        self.text_info_set.setWhatsThis("")
        self.text_info_set.setAccessibleName("")
        self.text_info_set.setAccessibleDescription("")
        self.text_info_set.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.text_info_set.setText("<insert set text here>")
        self.text_info_set.setAlignment(QtCore.Qt.AlignCenter)
        self.text_info_set.setObjectName("text_info_set")
        self.btn_ok_set = QtWidgets.QPushButton(self.frame_set)
        self.btn_ok_set.setGeometry(QtCore.QRect(200, 100, 140, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok_set.setFont(font)
        self.btn_ok_set.setToolTip("")
        self.btn_ok_set.setStatusTip("")
        self.btn_ok_set.setWhatsThis("")
        self.btn_ok_set.setAccessibleName("")
        self.btn_ok_set.setAccessibleDescription("")
        self.btn_ok_set.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_ok_set.setText("OK")
        self.btn_ok_set.setObjectName("btn_ok_set")
        self.gs_bg.raise_()
        self.gs_btn_help.raise_()
        self.gs_btn_quit.raise_()
        self.gs_opp_slot_1.raise_()
        self.gs_opp_slot_2.raise_()
        self.gs_opp_slot_3.raise_()
        self.gs_opp_slot_4.raise_()
        self.gs_opp_slot_5.raise_()
        self.gs_opp_slot_6.raise_()
        self.gs_opp_slot_7.raise_()
        self.gs_opp_slot_8.raise_()
        self.gs_opp_slot_9.raise_()
        self.gs_player_slot_1.raise_()
        self.gs_player_slot_2.raise_()
        self.gs_player_slot_3.raise_()
        self.gs_player_slot_4.raise_()
        self.gs_player_slot_5.raise_()
        self.gs_player_slot_6.raise_()
        self.gs_player_slot_7.raise_()
        self.gs_player_slot_8.raise_()
        self.gs_player_slot_9.raise_()
        self.gs_player_hand_1.raise_()
        self.gs_player_hand_2.raise_()
        self.gs_player_hand_3.raise_()
        self.gs_player_hand_4.raise_()
        self.gs_opp_hand_1.raise_()
        self.gs_opp_hand_2.raise_()
        self.gs_opp_hand_3.raise_()
        self.gs_opp_hand_4.raise_()
        self.gs_player_turn.raise_()
        self.gs_opp_turn.raise_()
        self.gs_player_set_1.raise_()
        self.gs_player_set_2.raise_()
        self.gs_player_set_3.raise_()
        self.gs_opp_set_3.raise_()
        self.gs_opp_set_2.raise_()
        self.gs_opp_set_1.raise_()
        self.gs_btn_endturn.raise_()
        self.gs_btn_stand.raise_()
        self.gs_flip_1.raise_()
        self.gs_flip_2.raise_()
        self.gs_flip_3.raise_()
        self.gs_flip_4.raise_()
        self.temp_gs_player_name.raise_()
        self.temp_gs_opp_name.raise_()
        self.gs_player_total.raise_()
        self.gs_opp_total.raise_()
        self.popup_set.raise_()
        self.popup_match.raise_()
        self.sw.addWidget(self.sw_game_screen)
        self.sw_help_screen = QtWidgets.QWidget()
        self.sw_help_screen.setObjectName("sw_help_screen")
        self.hs_btn_close = QtWidgets.QPushButton(self.sw_help_screen)
        self.hs_btn_close.setGeometry(QtCore.QRect(36, 32, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hs_btn_close.setFont(font)
        self.hs_btn_close.setAccessibleName("")
        self.hs_btn_close.setAccessibleDescription("")
        self.hs_btn_close.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.hs_btn_close.setText("BACK")
        self.hs_btn_close.setObjectName("hs_btn_close")
        self.hs_bg = QtWidgets.QLabel(self.sw_help_screen)
        self.hs_bg.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.hs_bg.setAccessibleName("")
        self.hs_bg.setAccessibleDescription("")
        self.hs_bg.setStyleSheet("background-color: lightgray")
        self.hs_bg.setText("")
        self.hs_bg.setObjectName("hs_bg")
        self.temp_hs_text = QtWidgets.QLabel(self.sw_help_screen)
        self.temp_hs_text.setGeometry(QtCore.QRect(46, 74, 1060, 720))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.temp_hs_text.setFont(font)
        self.temp_hs_text.setStyleSheet("background-color: transparent")
        self.temp_hs_text.setText("Pazaak is a game similar to Blackjack.\n"
"- players must reach a total of 20 (or as close as possible) without going over\n"
"- the player with the higher total wins the set\n"
"- 3 sets win the match\n"
"\n"
"At the beginning of the match, you will choose 10 cards to add to your deck. 4 of these cards will be randomly dealt to your hand. You may play cards from your hand to manipulate the total value on the table.\n"
"- you will only get one hand per match (make these cards last :)\n"
"- you may only play one hand card per turn\n"
"- dual cards (-/+) can be flipped to choose which action you want them to perform\n"
"\n"
"The game is turn based.\n"
"- players draw a card from the house\'s deck at the beginning of their turn\n"
"- on their turn, they may choose to play a card from hand (or not, strategy is key ;)\n"
"- finally, they can do one of two things:\n"
"[1] end turn, to pass the turn to the opponent\n"
"- at the end of their turn, if a player\'s total exceeds 20, they automatically lose the set\n"
"[2] stand, if they\'re happy with the total value on their side of the table\n"
"- if standing, they will not draw or play any additional cards during that set")
        self.temp_hs_text.setWordWrap(True)
        self.temp_hs_text.setObjectName("temp_hs_text")
        self.hs_bg.raise_()
        self.hs_btn_close.raise_()
        self.temp_hs_text.raise_()
        self.sw.addWidget(self.sw_help_screen)
        self.gridLayout.addWidget(self.sw, 0, 0, 1, 1)
        mw.setCentralWidget(self.cw)

        self.retranslateUi(mw)
        self.sw.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mw)

    def retranslateUi(self, mw):
        pass
