# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtd_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw(object):
    def setupUi(self, mw):
        mw.setObjectName("mw")
        mw.resize(1152, 864)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mw.sizePolicy().hasHeightForWidth())
        mw.setSizePolicy(sizePolicy)
        mw.setMinimumSize(QtCore.QSize(1152, 864))
        mw.setWindowTitle("Pazaak")
        mw.setAccessibleName("")
        mw.setAccessibleDescription("")
        mw.setStyleSheet("background-color: rgb(0, 0, 0);")
        mw.setWindowFilePath("")
        self.cw = QtWidgets.QWidget(mw)
        self.cw.setAccessibleName("")
        self.cw.setAccessibleDescription("")
        self.cw.setObjectName("cw")
        self.gridLayout = QtWidgets.QGridLayout(self.cw)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sw = QtWidgets.QStackedWidget(self.cw)
        self.sw.setMaximumSize(QtCore.QSize(1152, 864))
        self.sw.setAccessibleName("")
        self.sw.setAccessibleDescription("")
        self.sw.setObjectName("sw")
        self.sw_main_menu = QtWidgets.QWidget()
        self.sw_main_menu.setAccessibleName("")
        self.sw_main_menu.setAccessibleDescription("")
        self.sw_main_menu.setObjectName("sw_main_menu")
        self.mm_bg = QtWidgets.QLabel(self.sw_main_menu)
        self.mm_bg.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.mm_bg.setAccessibleName("")
        self.mm_bg.setAccessibleDescription("")
        self.mm_bg.setText("")
        self.mm_bg.setPixmap(QtGui.QPixmap("assets/bg_guide.png"))
        self.mm_bg.setObjectName("mm_bg")
        self.mm_btn_start = QtWidgets.QPushButton(self.sw_main_menu)
        self.mm_btn_start.setGeometry(QtCore.QRect(486, 342, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mm_btn_start.setFont(font)
        self.mm_btn_start.setAccessibleName("")
        self.mm_btn_start.setAccessibleDescription("")
        self.mm_btn_start.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.mm_btn_start.setText("START")
        self.mm_btn_start.setObjectName("mm_btn_start")
        self.mm_btn_help = QtWidgets.QPushButton(self.sw_main_menu)
        self.mm_btn_help.setGeometry(QtCore.QRect(486, 412, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mm_btn_help.setFont(font)
        self.mm_btn_help.setAccessibleName("")
        self.mm_btn_help.setAccessibleDescription("")
        self.mm_btn_help.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.mm_btn_help.setText("HELP")
        self.mm_btn_help.setObjectName("mm_btn_help")
        self.mm_btn_exit = QtWidgets.QPushButton(self.sw_main_menu)
        self.mm_btn_exit.setGeometry(QtCore.QRect(486, 482, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mm_btn_exit.setFont(font)
        self.mm_btn_exit.setAccessibleName("")
        self.mm_btn_exit.setAccessibleDescription("")
        self.mm_btn_exit.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.mm_btn_exit.setText("EXIT")
        self.mm_btn_exit.setObjectName("mm_btn_exit")
        self.temp_db_title_2 = QtWidgets.QLabel(self.sw_main_menu)
        self.temp_db_title_2.setGeometry(QtCore.QRect(516, 10, 120, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.temp_db_title_2.setFont(font)
        self.temp_db_title_2.setStyleSheet("background-color: orange")
        self.temp_db_title_2.setText("Main Menu")
        self.temp_db_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_db_title_2.setObjectName("temp_db_title_2")
        self.sw.addWidget(self.sw_main_menu)
        self.sw_deck_builder = QtWidgets.QWidget()
        self.sw_deck_builder.setAccessibleName("")
        self.sw_deck_builder.setAccessibleDescription("")
        self.sw_deck_builder.setObjectName("sw_deck_builder")
        self.db_bg = QtWidgets.QLabel(self.sw_deck_builder)
        self.db_bg.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.db_bg.setAccessibleName("")
        self.db_bg.setAccessibleDescription("")
        self.db_bg.setText("")
        self.db_bg.setPixmap(QtGui.QPixmap("assets/bg_guide.png"))
        self.db_bg.setObjectName("db_bg")
        self.temp_db_title = QtWidgets.QLabel(self.sw_deck_builder)
        self.temp_db_title.setGeometry(QtCore.QRect(516, 10, 120, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.temp_db_title.setFont(font)
        self.temp_db_title.setStyleSheet("background-color: orange")
        self.temp_db_title.setText("Deck Builder")
        self.temp_db_title.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_db_title.setObjectName("temp_db_title")
        self.db_btn_play = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_btn_play.setGeometry(QtCore.QRect(952, 20, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.db_btn_play.setFont(font)
        self.db_btn_play.setAccessibleName("")
        self.db_btn_play.setAccessibleDescription("")
        self.db_btn_play.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.db_btn_play.setText("PLAY MATCH")
        self.db_btn_play.setObjectName("db_btn_play")
        self.db_btn_back = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_btn_back.setGeometry(QtCore.QRect(20, 20, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.db_btn_back.setFont(font)
        self.db_btn_back.setAccessibleName("")
        self.db_btn_back.setAccessibleDescription("")
        self.db_btn_back.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.db_btn_back.setText("BACK TO MAIN")
        self.db_btn_back.setObjectName("db_btn_back")
        self.sw.addWidget(self.sw_deck_builder)
        self.sw_game_screen = QtWidgets.QWidget()
        self.sw_game_screen.setObjectName("sw_game_screen")
        self.temp_gs_title = QtWidgets.QLabel(self.sw_game_screen)
        self.temp_gs_title.setGeometry(QtCore.QRect(516, 10, 120, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.temp_gs_title.setFont(font)
        self.temp_gs_title.setStyleSheet("background-color: orange")
        self.temp_gs_title.setText("Game Screen")
        self.temp_gs_title.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_gs_title.setObjectName("temp_gs_title")
        self.gs_bg = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_bg.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.gs_bg.setAccessibleName("")
        self.gs_bg.setAccessibleDescription("")
        self.gs_bg.setText("")
        self.gs_bg.setPixmap(QtGui.QPixmap("assets/bg_guide.png"))
        self.gs_bg.setObjectName("gs_bg")
        self.gs_btn_help = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_btn_help.setGeometry(QtCore.QRect(16, 818, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gs_btn_help.setFont(font)
        self.gs_btn_help.setAccessibleName("")
        self.gs_btn_help.setAccessibleDescription("")
        self.gs_btn_help.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.gs_btn_help.setText("?")
        self.gs_btn_help.setObjectName("gs_btn_help")
        self.gs_btn_quit = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_btn_quit.setGeometry(QtCore.QRect(846, 790, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gs_btn_quit.setFont(font)
        self.gs_btn_quit.setAccessibleName("")
        self.gs_btn_quit.setAccessibleDescription("")
        self.gs_btn_quit.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.gs_btn_quit.setText("QUIT MATCH")
        self.gs_btn_quit.setObjectName("gs_btn_quit")
        self.gs_bg.raise_()
        self.temp_gs_title.raise_()
        self.gs_btn_help.raise_()
        self.gs_btn_quit.raise_()
        self.sw.addWidget(self.sw_game_screen)
        self.sw_help_screen = QtWidgets.QWidget()
        self.sw_help_screen.setObjectName("sw_help_screen")
        self.temp_hs_title = QtWidgets.QLabel(self.sw_help_screen)
        self.temp_hs_title.setGeometry(QtCore.QRect(516, 10, 120, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.temp_hs_title.setFont(font)
        self.temp_hs_title.setStyleSheet("background-color: orange")
        self.temp_hs_title.setText("Help Screen")
        self.temp_hs_title.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_hs_title.setObjectName("temp_hs_title")
        self.hs_btn_close = QtWidgets.QPushButton(self.sw_help_screen)
        self.hs_btn_close.setGeometry(QtCore.QRect(20, 20, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hs_btn_close.setFont(font)
        self.hs_btn_close.setAccessibleName("")
        self.hs_btn_close.setAccessibleDescription("")
        self.hs_btn_close.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.hs_btn_close.setText("BACK")
        self.hs_btn_close.setObjectName("hs_btn_close")
        self.hs_bg = QtWidgets.QLabel(self.sw_help_screen)
        self.hs_bg.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.hs_bg.setAccessibleName("")
        self.hs_bg.setAccessibleDescription("")
        self.hs_bg.setText("")
        self.hs_bg.setPixmap(QtGui.QPixmap("assets/bg_guide.png"))
        self.hs_bg.setObjectName("hs_bg")
        self.temp_hs_text = QtWidgets.QLabel(self.sw_help_screen)
        self.temp_hs_text.setGeometry(QtCore.QRect(46, 72, 1060, 720))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.temp_hs_text.setFont(font)
        self.temp_hs_text.setStyleSheet("background-color: lightgray")
        self.temp_hs_text.setText("Pazaak is a game similar to Blackjack.\n"
"- players must reach a total of 20 (or as close as possible) without going over\n"
"- the player with the higher total wins the set\n"
"- 3 sets win the match\n"
"\n"
"At the beginning of the match, you will choose 10 cards to add to your side deck. 4 of these cards will be randomly dealt to your hand. You may play cards from your hand to manipulate the total value on the table.\n"
"- you will only get one hand per match (make these cards last :)\n"
"- you may only play one hand card per turn\n"
"- dual cards (-/+) can be flipped to choose which action you want them to perform\n"
"\n"
"The game is turn based.\n"
"- players draw a card from the house\'s deck at the beginning of their turn\n"
"- then, they may choose to play a card from hand (or not, strategy is key ;)\n"
"- finally, they can do one of two things:\n"
"[1] end turn, to pass the turn to the opponent\n"
"- at the end of their turn, if the player has a total over 20, they automatically lose the set\n"
"[2] stand, if they\'re happy with the total value on their side of the table\n"
"- if standing, they will not draw or play any additional cards during that set")
        self.temp_hs_text.setWordWrap(True)
        self.temp_hs_text.setObjectName("temp_hs_text")
        self.hs_bg.raise_()
        self.hs_btn_close.raise_()
        self.temp_hs_title.raise_()
        self.temp_hs_text.raise_()
        self.sw.addWidget(self.sw_help_screen)
        self.gridLayout.addWidget(self.sw, 0, 0, 1, 1)
        mw.setCentralWidget(self.cw)

        self.retranslateUi(mw)
        self.sw.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mw)

    def retranslateUi(self, mw):
        pass
