# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtd_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw(object):
    def setupUi(self, mw):
        mw.setObjectName("mw")
        mw.resize(1152, 864)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mw.sizePolicy().hasHeightForWidth())
        mw.setSizePolicy(sizePolicy)
        mw.setMinimumSize(QtCore.QSize(1152, 864))
        mw.setWindowTitle("Pazaak")
        mw.setAccessibleName("")
        mw.setAccessibleDescription("")
        mw.setStyleSheet("background-color: rgb(0, 0, 0);")
        mw.setWindowFilePath("")
        self.cw = QtWidgets.QWidget(mw)
        self.cw.setAccessibleName("")
        self.cw.setAccessibleDescription("")
        self.cw.setObjectName("cw")
        self.gridLayout = QtWidgets.QGridLayout(self.cw)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sw = QtWidgets.QStackedWidget(self.cw)
        self.sw.setMaximumSize(QtCore.QSize(1152, 864))
        self.sw.setAccessibleName("")
        self.sw.setAccessibleDescription("")
        self.sw.setObjectName("sw")
        self.sw_main_menu = QtWidgets.QWidget()
        self.sw_main_menu.setAccessibleName("")
        self.sw_main_menu.setAccessibleDescription("")
        self.sw_main_menu.setObjectName("sw_main_menu")
        self.mm_bg = QtWidgets.QLabel(self.sw_main_menu)
        self.mm_bg.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.mm_bg.setAccessibleName("")
        self.mm_bg.setAccessibleDescription("")
        self.mm_bg.setText("")
        self.mm_bg.setPixmap(QtGui.QPixmap("assets/bg_guide.png"))
        self.mm_bg.setObjectName("mm_bg")
        self.mm_btn_start = QtWidgets.QPushButton(self.sw_main_menu)
        self.mm_btn_start.setGeometry(QtCore.QRect(476, 336, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mm_btn_start.setFont(font)
        self.mm_btn_start.setAccessibleName("")
        self.mm_btn_start.setAccessibleDescription("")
        self.mm_btn_start.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.mm_btn_start.setText("START")
        self.mm_btn_start.setObjectName("mm_btn_start")
        self.mm_btn_help = QtWidgets.QPushButton(self.sw_main_menu)
        self.mm_btn_help.setGeometry(QtCore.QRect(476, 406, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mm_btn_help.setFont(font)
        self.mm_btn_help.setAccessibleName("")
        self.mm_btn_help.setAccessibleDescription("")
        self.mm_btn_help.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.mm_btn_help.setText("HELP")
        self.mm_btn_help.setObjectName("mm_btn_help")
        self.mm_btn_exit = QtWidgets.QPushButton(self.sw_main_menu)
        self.mm_btn_exit.setGeometry(QtCore.QRect(476, 476, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mm_btn_exit.setFont(font)
        self.mm_btn_exit.setAccessibleName("")
        self.mm_btn_exit.setAccessibleDescription("")
        self.mm_btn_exit.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.mm_btn_exit.setText("EXIT")
        self.mm_btn_exit.setObjectName("mm_btn_exit")
        self.temp_mm_title = QtWidgets.QLabel(self.sw_main_menu)
        self.temp_mm_title.setGeometry(QtCore.QRect(456, 110, 240, 60))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.temp_mm_title.setFont(font)
        self.temp_mm_title.setStyleSheet("background-color: transparent;")
        self.temp_mm_title.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_mm_title.setObjectName("temp_mm_title")
        self.sw.addWidget(self.sw_main_menu)
        self.sw_deck_builder = QtWidgets.QWidget()
        self.sw_deck_builder.setAccessibleName("")
        self.sw_deck_builder.setAccessibleDescription("")
        self.sw_deck_builder.setObjectName("sw_deck_builder")
        self.db_bg = QtWidgets.QLabel(self.sw_deck_builder)
        self.db_bg.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.db_bg.setAccessibleName("")
        self.db_bg.setAccessibleDescription("")
        self.db_bg.setText("")
        self.db_bg.setPixmap(QtGui.QPixmap("assets/bg_guide.png"))
        self.db_bg.setObjectName("db_bg")
        self.temp_db_title = QtWidgets.QLabel(self.sw_deck_builder)
        self.temp_db_title.setGeometry(QtCore.QRect(446, 24, 260, 60))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.temp_db_title.setFont(font)
        self.temp_db_title.setStyleSheet("background-color: transparent;")
        self.temp_db_title.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_db_title.setObjectName("temp_db_title")
        self.db_btn_play = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_btn_play.setGeometry(QtCore.QRect(1048, 40, 64, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.db_btn_play.setFont(font)
        self.db_btn_play.setAccessibleName("")
        self.db_btn_play.setAccessibleDescription("")
        self.db_btn_play.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.db_btn_play.setText(">")
        self.db_btn_play.setObjectName("db_btn_play")
        self.db_btn_back = QtWidgets.QPushButton(self.sw_deck_builder)
        self.db_btn_back.setGeometry(QtCore.QRect(40, 40, 64, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.db_btn_back.setFont(font)
        self.db_btn_back.setAccessibleName("")
        self.db_btn_back.setAccessibleDescription("")
        self.db_btn_back.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.db_btn_back.setText("<")
        self.db_btn_back.setObjectName("db_btn_back")
        self.sw.addWidget(self.sw_deck_builder)
        self.sw_game_screen = QtWidgets.QWidget()
        self.sw_game_screen.setObjectName("sw_game_screen")
        self.temp_gs_title = QtWidgets.QLabel(self.sw_game_screen)
        self.temp_gs_title.setGeometry(QtCore.QRect(436, 24, 280, 60))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.temp_gs_title.setFont(font)
        self.temp_gs_title.setStyleSheet("background-color: transparent;")
        self.temp_gs_title.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_gs_title.setObjectName("temp_gs_title")
        self.gs_bg = QtWidgets.QLabel(self.sw_game_screen)
        self.gs_bg.setGeometry(QtCore.QRect(0, 0, 1152, 864))
        self.gs_bg.setAccessibleName("")
        self.gs_bg.setAccessibleDescription("")
        self.gs_bg.setText("")
        self.gs_bg.setPixmap(QtGui.QPixmap("assets/bg_guide.png"))
        self.gs_bg.setObjectName("gs_bg")
        self.gs_btn_help = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_btn_help.setGeometry(QtCore.QRect(544, 130, 64, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.gs_btn_help.setFont(font)
        self.gs_btn_help.setAccessibleName("")
        self.gs_btn_help.setAccessibleDescription("")
        self.gs_btn_help.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.gs_btn_help.setText("?")
        self.gs_btn_help.setObjectName("gs_btn_help")
        self.gs_btn_quit = QtWidgets.QPushButton(self.sw_game_screen)
        self.gs_btn_quit.setGeometry(QtCore.QRect(40, 40, 64, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.gs_btn_quit.setFont(font)
        self.gs_btn_quit.setAccessibleName("")
        self.gs_btn_quit.setAccessibleDescription("")
        self.gs_btn_quit.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;\n"
"}\n"
"")
        self.gs_btn_quit.setText("<")
        self.gs_btn_quit.setObjectName("gs_btn_quit")
        self.gs_bg.raise_()
        self.temp_gs_title.raise_()
        self.gs_btn_help.raise_()
        self.gs_btn_quit.raise_()
        self.sw.addWidget(self.sw_game_screen)
        self.gridLayout.addWidget(self.sw, 1, 0, 1, 1)
        mw.setCentralWidget(self.cw)

        self.retranslateUi(mw)
        self.sw.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mw)

    def retranslateUi(self, mw):
        _translate = QtCore.QCoreApplication.translate
        self.temp_mm_title.setText(_translate("mw", "Pazaak"))
        self.temp_db_title.setText(_translate("mw", "Deck Builder"))
        self.temp_gs_title.setText(_translate("mw", "Game Screen"))
